Updating install script Updating git hooks to call docker for testing Fixing docker build scripts for docker-compose

diff --git a/bin/git-hooks/pre-commit b/bin/git-hooks/pre-commit
--- a/bin/git-hooks/pre-commit
+++ b/bin/git-hooks/pre-commit
@@ -1,6 +1,53 @@
-#!/usr/bin/env bash
-echo "[pre-commit] Running linter"
-for file in  $(git diff --cached --name-status | awk '$1 != "R" { print $2 }' });
+#!/bin/sh
+
+# @source: https://gist.github.com/ronanguilloux/11f6a788358577474ab4
+# @link http://tech.zumba.com/2014/04/14/control-code-quality/
+
+PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
+STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
+
+# Determine if a file list is passed
+if [ "$#" -eq 1 ]
+then
+    oIFS=$IFS
+    IFS='
+    '
+    SFILES="$1"
+    IFS=$oIFS
+fi
+SFILES=${SFILES:-$STAGED_FILES_CMD}
+
+echo "[pre-commit] Checking PHP Lint..."
+for FILE in $SFILES
 do
-    echo $file
-done;
+    php -l -d display_errors=0 $PROJECT/$FILE
+    if [ $? != 0 ]
+    then
+        echo "[pre-commit] Fix the error before commit."
+        exit 1
+    fi
+    FILES="$FILES $PROJECT/$FILE"
+done
+
+if [ "$FILES" != "" ]
+then
+    echo "[pre-commit] Running Code Sniffer..."
+    phpcs --standard=PSR2 module -n
+    if [ $? != 0 ]
+    then
+        echo "[pre-commit] Fix the error before commit."
+        exit 1
+    fi
+
+    echo "[pre-commit] Running Mess detector..."
+    phpmd module text codesize,design,controversial --suffixes php --exclude "*Test*"
+    if [ $? != 0 ]
+    then
+        echo "[pre-commit] Fix the error before commit."
+        exit 1
+    fi
+fi
+
+echo "[pre-commit] All Checks good"
+
+exit $?
